#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Update package lists
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
echo '
frontend sammykingx.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 501350-web-01 35.174.200.187:80
        server 501350-web-02 54.237.102.217:80
' >> /etc/haproxy/haproxy.cfg

service haproxy restart
