#!/bin/bash

# Install and enable ufw
sudo apt-get install ufw
sudo ufw enable

# Allow SSH (port 22), HTTPS (port 443), and HTTP (port 80) traffic
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Deny all other incoming traffic
sudo ufw default deny incoming

# Enable ufw to start filtering traffic based on the configured rules
sudo ufw enable
