#!/usr/bin/env bash
# Configures an Ubuntu server a localhost resolves to 127.0.0.0 and facebook.com resolves to 8.8.8.8

sudo bash -c 'echo "127.0.0.2	localhost" > /etc/hosts'
sudo bash -c 'echo "8.8.8.8	facebook.com" >> /etc/hosts'






