#!/usr/bin/env bash
# Check if script is run as root
if [ "$(id -u)" -ne 0 ]; then
    echo "Please run this script as root"
    exit 1
fi

# Set Nginx user to nginx
sed -i 's/^#\?user\s*[^;]*/user nginx/' nginx.conf


# Set Nginx to listen on all active IPs on port 8080
sed -i 's/listen\s*[^;]*/listen *:8080;/' /etc/nginx/sites-available/default

# Restart Nginx
#service nginx restart

#echo "Nginx configured successfully"
