#!/usr/bin/env bash
# Define server and private key file
server="ubuntu@3.84.239.244"
private_key="~/.ssh/id_rsa.pub"

# SSH connection using single-character flags
ssh -i "$private_key" ubuntu@"$server"
